### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by tylorr** [andreaferretti/rxnim#2]
I'd like to contribute to this project, I have a couple of questions for you. Was there a specific Rx implementation you were using to guide this one? Should I submit pull requests or should I just work on my own fork for now?

**Comment by andreaferretti** [comment]
Hi @tylorr I'd be happy if you want to take over the project. As you can see, this was never published on nimble, and should be considered a little experiment more than an actual Rx implementation. I did not follow any particular implementation

That said, it may be useful as a starting point. As for PR of forks: since I have no plans to mantain this, I think a fork is fine. If you want to start from scratch and steal bits that may be useful, that is fine for me as well.

**Comment by tylorr** [comment]
Ok, I'll fork the project and see how far I can get :D
